### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by fredbierman** [edwinvdpol/com.foscam#1]
**Describe the issue**
Als ik een camera wil toevoegen krijg ik een error 404 bij het verbinden

**To Reproduce**
Hostnaam invullen,poort,etc  en geeft dan een error 404

**Expected behavior**

**Screenshots**

**Camera (please complete the following information):**
- Homey firmware version: 2.0.4
- App version 1.0.0
- Camera model Foscam PT camera

**Additional context**
error is :404-"<HTML><HEAD><TITLE>404 Not found..

**Comment by edwinvdpol** [comment]
Kun je wel de [web interface benaderen](https://www.foscam.com/faqs/view.html?id=17) via je webbrowser op `http://[ip]:[port]`?
Zo ja, kun je URI `/cgi-bin/CGIProxy.fcgi` wel benaderen, of `/CGIProxy.fcgi`?
Kun je de camera ook bereiken via de [Foscam IP camera tool](http://www.foscam.com/download-center/software-tools.html)?
Gegevens kloppen verder?

**Comment by fredbierman** [comment]
Beste Edwin,
Ik kan hem via de web interface benaderen 

![image](https://user-images.githubusercontent.com/48022347/53447881-78aff600-3a16-11e9-8014-1d34da08b5c5.png)

en kan hem ook benaderen via de IP camera tools.Ik ben niet bekent met de URI (newbie)
Verders alles ingegeven via de app maar bij verbinden geen hij die fout.
Waarschijnlijk doe ik iets fout ,ben op dit gebied een beginner maar app zou ik graag willen gebruiken

**Comment by fredbierman** [comment]
Beste Edwin,

Na het inlog scherm krijg ik dit scherm
![image](https://user-images.githubusercontent.com/48022347/53448321-6b473b80-3a17-11e9-9d5d-a2675a054d15.png)

Zou dit het probleem zijn ?

**Comment by edwinvdpol** [comment]
Hi Fred,

Dat zou geen probleem moeten zijn.
Welk scherm of wat krijg je te zien als je naar http://192.168.2.7:81/cgi-bin/CGIProxy.fcgi gaat?
Kun je hier, of via Slack een screenshot sturen van je instellingen?
Tot slot, welke firmware heeft jouw camera?

**Comment by fredbierman** [comment]
Beste Edwin,
 
Dit is dus het scherm wat ik krijg als ik via de link inlog.
Info camera
 

Device ID
  00626E4927C1

  Device Firmware Version
  11.37.2.59

  Device Embeded Web UI Version
  2.0.10.12

  Alias
  Home-Voordeur
 
Groeten,
 
Fred
 

 
Van: E. van de Pol <notifications@github.com> 
Verzonden: dinsdag 26 februari 2019 23:04
Aan: edwinvdpol/com.foscam <com.foscam@noreply.github.com>
CC: fredbierman <fred.bierman@zonnet.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [edwinvdpol/com.foscam] Error 404 (#1)
 
Hi Fred,
Dat zou geen probleem moeten zijn.
Welk scherm of wat krijg je te zien als je naar http://192.168.2.7:81/cgi-bin/CGIProxy.fcgi gaat?
Kun je hier, of via Slack een screenshot sturen van je instellingen?
Tot slot, welke firmware heeft jouw camera?

**Comment by edwinvdpol** [comment]
Maar je hoeft toch niet in te loggen als je naar http://192.168.2.7:81/cgi-bin/CGIProxy.fcgi gaat?
Ik verwacht meer een webpagina met het volgende:
```
<CGI_Result>
    <result>-3</result>
</CGI_Result>
```

**Comment by fredbierman** [comment]
Nee,zodra ik op de link druk krijg ik dit scherm
 
Fred
 
Van: E. van de Pol <notifications@github.com> 
Verzonden: woensdag 27 februari 2019 7:56
Aan: edwinvdpol/com.foscam <com.foscam@noreply.github.com>
CC: fredbierman <fred.bierman@zonnet.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [edwinvdpol/com.foscam] Error 404 (#1)
 
Maar je hoeft toch niet in te loggen als je naar http://192.168.2.7:81/cgi-bin/CGIProxy.fcgi gaat?
Ik verwacht meer een webpagina met het volgende:
<CGI_Result>
    <result>-3</result>
</CGI_Result>

**Comment by edwinvdpol** [comment]
Oké, vreemd! Kun je exact aangeven welk modelnummer je camera is (bijv. FI9901EP)?
Dan ga ik het even verder proberen uit te zoeken.

**Comment by fredbierman** [comment]
Hi Edwin,
 
Heb dit nu bij al mijn camera’s gedaan en bij een (dome) krijg ik de info zoals je beschrijft de andere geeft hij die fout.
Ik ga er vanavond nog eens nakijken maar heel erg bedankt voor je hulp
 
Groeten,
 
Fred
 
Van: E. van de Pol <notifications@github.com> 
Verzonden: woensdag 27 februari 2019 7:56
Aan: edwinvdpol/com.foscam <com.foscam@noreply.github.com>
CC: fredbierman <fred.bierman@zonnet.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [edwinvdpol/com.foscam] Error 404 (#1)
 
Maar je hoeft toch niet in te loggen als je naar http://192.168.2.7:81/cgi-bin/CGIProxy.fcgi gaat?
Ik verwacht meer een webpagina met het volgende:
<CGI_Result>
    <result>-3</result>
</CGI_Result>

**Comment by edwinvdpol** [comment]
Fred, kun je nog aangeven welk modelnummer en type je camera is die niet werkt (bijv. FI9901EP)?
Alvast bedankt.

**Comment by fredbierman** [comment]
Hi Edwin,
 
Hierbij de gegevens :
 
1.FI8910W : werkt niet error 404
2.FI8904W : werkt niet error 404
3.FI9851P : werkt en kan ik installeren in Homey
 
Vraagje omdat ik hiermee niet zo bekend ben maar kun je Live beelden hiermee naar binnen halen of alleen een flow maken en dan een screenshot sturen
 
Groeten en succes,
Fred
 
Van: E. van de Pol <notifications@github.com> 
Verzonden: woensdag 27 februari 2019 18:11
Aan: edwinvdpol/com.foscam <com.foscam@noreply.github.com>
CC: fredbierman <fred.bierman@zonnet.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [edwinvdpol/com.foscam] Error 404 (#1)
 
Fred, kun je nog aangeven welk modelnummer en type je camera is die niet werkt (bijv. FI9901EP)?
Alvast bedankt.

**Comment by edwinvdpol** [comment]
Bedankt voor de gegevens. Iemand anders heeft ook problemen met de FI8904W. Hierover zal ik contact opnemen met Foscam. Ik laat je weten zodra ik meer weet.

Verder is het nu alleen nog mogelijk of een screenshot te nemen en deze te versturen via e-mail.
In de toekomst zullen eventueel nog andere functies aan toegevoegd worden.

**Comment by edwinvdpol** [comment]
Hi Fred,

Ik heb antwoord van Foscam gehad.

> All most all of the camera support the CGI command.
> The difference is that the CGI command supported is not the same.
> The old model FI89xx could only support some simple command like snapshot and video streams.

Ik kan er dus weinig aan doen helaas. Ik zal dit opnemen in de README van de app bij de volgende release.

**Comment by fredbierman** [comment]
Hi Edwin,
 
Dat is jammer maar wel duidelijk nu,dus maar sparen voor nieuwere camera’s
 
Bedankt voor de moeite
 
Fred
 
Van: E. van de Pol <notifications@github.com> 
Verzonden: donderdag 28 februari 2019 9:36
Aan: edwinvdpol/com.foscam <com.foscam@noreply.github.com>
CC: fredbierman <fred.bierman@zonnet.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [edwinvdpol/com.foscam] Error 404 (#1)
 
Hi Fred,
Ik heb antwoord van Foscam gehad.
All most all of the camera support the CGI command.
The difference is that the CGI command supported is not the same.
The old model FI89xx could only support some simple command like snapshot and video streams.
Ik kan er dus weinig aan doen helaas. Ik zal dit opnemen in de README van de app bij de volgende release.
