### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by asteman** [edwinvdpol/com.foscam#12]
Installed v2.0.0 and tried a few snapshots sending to telegram bot. Worked great! Added 3 more cams and then it stopped working with the logs pasted below.

Any ideas what I might have done wrong?

(node:15397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2) 
(node:15397) UnhandledPromiseRejectionWarning: Error: Please configure your SMTP settings. at Mail.send (/lib/Mail.js:24:19) at Homey.app.getSnapshot.then.result (/lib/Device.js:308:32) at at process._tickCallback (internal/process/next_tick.js:189:7) 
✓ cam10_Garaget taking snapshot 
(node:15397) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
(node:15397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) 
(node:15397) UnhandledPromiseRejectionWarning: Error: Please configure your SMTP settings. at Mail.send (/lib/Mail.js:24:19) at Homey.app.getSnapshot.then.result (/lib/Device.js:308:32) at at process._tickCallback (internal/process/next_tick.js:189:7) 
✓ cam10_Garaget taking snapshot 
✓ out_back_porch initiated 
✓ Cam6_ute_forradet initiated 
✓ cam10_Garaget initiated 
✓ cam9_ute_ytterdorr initiated 
✓ out_back_porch motion command is `0` 
✓ Cam6_ute_forradet motion command is `1` 
✓ cam10_Garaget motion command is `1` 
✓ cam9_ute_ytterdorr motion command is `1` 
✓ Foscam App running

**Comment by edwinvdpol** [comment]
You have to configure your SMTP settings, even though you only use Telegram to send the screenshot.
This is a known bug (#10). Haven't got a lot of time on my hands, but will fix this soon.

**Comment by asteman** [comment]
Thanks, that did the trick! Just entered dummy settings.
