### ISSUE TITLE
FI8919W unsupported

### ISSUE THREAD

**Issue by RonBartsch** [edwinvdpol/com.foscam#13]
Question the FI89xx series is stated as unsupported, I have an FI8918W camera and I'm curious will it never work / be supported ?

**Comment by edwinvdpol** [comment]
It guess it will never work. You can try if you want, and let me know the results. Foscam told me that serie doesn't support the CGI interface. As long they don't support it, the app won't work unfortunately.

**Comment by RonBartsch** [comment]
Sadly it's not working, I receive an error "Ongeldig antwoord van netwerkapparaat gekregen" while adding the camera.

**Comment by edwinvdpol** [comment]
That is too bad... Thanks!
