### ISSUE TITLE
Na update naar versie 2.01 geen verbinding meer

### ISSUE THREAD

**Issue by Itsmmai** [edwinvdpol/com.foscam#14]
Vandaag update ontvangen nu geen verbinding meer met camera. Error: getaddrinfo ENOTFOUND undefined undefined: 80

Foscam FI9821P V2

Tot update werkte alles perfect.

Groet, Ab

**Comment by edwinvdpol** [comment]
Hi Ab, je moet de camera's opnieuw toevoegen, zie de changelog 😉

**Comment by Itsmmai** [comment]
Balen, maar ga het uitproberen. Changelog is oude versie nog bij mij ☹


Van: Edwin van de Pol <notifications@github.com>
Beantwoorden - Aan: "edwinvdpol/com.foscam" <reply@reply.github.com>
Datum: maandag 17 juni 2019 om 20:29
Aan: "edwinvdpol/com.foscam" <com.foscam@noreply.github.com>
CC: Ab Helversteijn-Smit <ab@helversteijn-smit.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [edwinvdpol/com.foscam] Na update naar versie 2.01 geen verbinding meer (#14)


Hi Ab, je moet de camera's opnieuw toevoegen, zie de changelog 😉

**Comment by edwinvdpol** [comment]
Je hebt gelijk! Ik zal vanavond even mergen!

**Comment by edwinvdpol** [comment]
Merged!
