### ISSUE TITLE
Email snapshot

### ISSUE THREAD

**Issue by FredSanPedro** [edwinvdpol/com.foscam#15]
Hi Edwin, 
 To send a snapshot I suppose that I have to configure the app and fill-in the userid and password off my email account. But is that reliable???
  To send an email with the snapshots my email address should be sufficient, isn’t it?
Kind regards,
Fred.

**Comment by edwinvdpol** [comment]
Hi Fred,

No it is not. Homey does not have a build in [SMTP server](https://serversmtp.com/what-is-smtp-server/), so you are required to use an external outgoing SMTP server. Homey will connect to the server, and that server will send the email. You do have to enter all fields, if you want to use the _Foscam app_ to send the email.

Kind regards,
Edwin

**Comment by edwinvdpol** [comment]
Closed due inactivity.

**Comment by FredSanPedro** [comment]
Hi Edwin,

Ik heb een Gmail account en Google geeft deze waarschuwing. Moet ik dat negeren?

Groet,
Fred

**Comment by FredSanPedro** [comment]
Hai Edwin, laat maar, ik heb een apart Gmail account aangemaakt en het werkt nu. Bedankt!


Begin doorgestuurd bericht:

**Comment by edwinvdpol** [comment]
Top!! ;-)
