### ISSUE TITLE
Issue with FI9900P

### ISSUE THREAD

**Issue by Fire69** [edwinvdpol/com.foscam#16]
Hi,

I just installed the app and added my 3 camera's. 
Both the F9821W's work fine, but the FI9900P shows an exclamation mark.
When opening the device I get 'Apparaat niet beschikbaar' 'Ongeldig antwoord van apparaat gekregen'.
It must be communicating ok up to some level because when the device was added it did detect the name correctly.

**Comment by edwinvdpol** [comment]
Hi,

Can you please post a part of the log file when the error occurred?

**Comment by Fire69** [comment]
✕ FI9900P_Garage Ongeldig antwoord van apparaat gekregen 
✕ FI9900P_Garage Ongeldig antwoord van apparaat gekregen 
✕ FI9900P_Garage Ongeldig antwoord van apparaat gekregen 
✕ FI9900P_Garage Ongeldig antwoord van apparaat gekregen 
✕ FI9900P_Garage Ongeldig antwoord van apparaat gekregen 
✕ FI9900P_Garage Ongeldig antwoord van apparaat gekregen 
✕ FI9900P_Garage Ongeldig antwoord van apparaat gekregen 
✕ FI9900P_Garage Ongeldig antwoord van apparaat gekregen 
✓ FI9900P_Garage refresh interval set to 60 seconds 
✕ FI9900P_Garage Ongeldig antwoord van apparaat gekregen 
✓ FI9900P_Garage set motion command to `0` 
✓ FI9900P_Garage is initiating 
✓ Found device: FI9900P_Garage (FI9900P+V5) 
✓ Searching device 
✓ Pairing started


I'll try the cgi when I get back home!

**Comment by edwinvdpol** [comment]
What do you get as a response when you try this URL?

`http://[ip]:[port]/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig&usr=[user]&pwd=[pass]`

(The same as before, but minus the 1.)

**Comment by edwinvdpol** [comment]
I solved the problem and the new version is submitted at Athom.

**Comment by Fire69** [comment]
Nice!
I'll let you know if it's OK when the update is available.

**Comment by edwinvdpol** [comment]
Update is published!

**Comment by Fire69** [comment]
Super, it's working now!
(I did have to remove and add the camera again)

Thanks a lot!

**Comment by edwinvdpol** [comment]
Yes, that is true. There was an issue when adding a device for certain type of cameras.
Great to hear it is working again, and thank you for your feedback!

Closing, issue is solved 👍
