### ISSUE TITLE
Fi9818w v1

### ISSUE THREAD

**Issue by dajojonl** [edwinvdpol/com.foscam#17]
This camera adds when using ptz camera, but it says got incorrect answer from camera and doesn't do anything.

**Comment by edwinvdpol** [comment]
What does the log say? In the device settings, is there a V at the Pan-Tilt setting?

**Comment by dajojonl** [comment]
✕ YuCam Rear Ongeldig antwoord van apparaat gekregen

**Comment by dajojonl** [comment]
Misschien te oude versie ofzo?
Heb em wel geupdate naar laatste firmware.
Het heeft als goed is de nieuwere versie inlog. Dat schijnt te werken of half gezien ie de cam wel ziet en toevoegde.

**Comment by dajojonl** [comment]
Camera has (App shows unknown though):
Sd-card    No
Pan/Tilt   Yes
Zoom       No
RS485      No
WPS         No
P2P          No
ONVIF      Yes
movement detection Yes

But none shows in advanced settings as App gets unknown reply from camera.

**Comment by dajojonl** [comment]
http://192.168.2.14/cgi-bin/CGIProxy.fcgi?cmd=getDevInfo&usr=me&pwd=pw

<CGI_Result> <result>0</result> <productName>FI9818W</productName> <serialNo>0000000000000001</serialNo> <devName>YuCam Rear</devName> <mac>XXXXXXXXXXX</mac> <year>2019</year> <mon>7</mon> <day>22</day> <hour>10</hour> <min>57</min> <sec>16</sec> <timeZone>-7200</timeZone> <firmwareVer>1.3.1.13</firmwareVer> <hardwareVer>1.2.1.1</hardwareVer> </CGI_Result>
Mac obviously masked... SNo: 1 is correct yes :-)

http://192.168.2.14/cgi-bin/CGIProxy.fcgi?cmd=motionCommand&usr=me&pwd=pw
<CGI_Result> <result>-3</result> </CGI_Result>

In your file API.js @ master:
try { let device = await this.get('getDevInfo'); let image = await this.get('getImageSetting'); let mirror = await this.get('getMirrorAndFlipSetting'); let motion = await this.get(motionCommand); let product = await this.get('getProductAllInfo'); let presets = await this.get('getPTZPresetPointList');

motionCommand misses the ' '
Is this correct?
Getimage result 0
Mirrorflip result 0
Getproductallinfo result -3
Ptz list result 0 + list


Cam responds to fcgi obviously so somewhere there is some wrong character or something missing i guess.

**Comment by edwinvdpol** [comment]
Hi,

> motionCommand misses the ' '
> Is this correct?

Yes, I use a variable there, because the getMotionDetect command is different for some camera's.

> http://192.168.2.14/cgi-bin/CGIProxy.fcgi?cmd=motionCommand&usr=me&pwd=pw
> CGI_Result> result>-3 /result> /CGI_Result>
The cmd `motionCommand` is not a command itself. It refers to the `getMotionConfig` or `getMotionConfig1`. The `-3` result is an invalid request.

Please read the code more thoroughly :wink:

But, back to the problem itself...

When you try the following URL, what does it say?
`http://<ip>:<port>/cgi-bin/CGIProxy.fcgi&cmd=getPTZPresetPointList&usr=me&pwd=pw`

-- Edwin

**Comment by dajojonl** [comment]
Yes i seen it in code , sorry been long time ago :-)

http://192.168.2.14/cgi-bin/CGIProxy.fcgi?cmd=getPTZPresetPointList&usr=me&pwd=pw

<code>
<CGI_Result> <result>0</result> <cnt>5</cnt> <point0>TopMost</point0> <point1>BottomMost</point1> <point2>LeftMost</point2> <point3>RightMost</point3> <point4>Center</point4> <point5></point5> <point6></point6> <point7></point7> <point8></point8> <point9></point9> <point10></point10> <point11></point11> <point12></point12> <point13></point13> <point14></point14> <point15></point15> </CGI_Result>
</code>

**Comment by edwinvdpol** [comment]
Please use [quotes](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code), now it is all just one line.

**Comment by dajojonl** [comment]
Ah that was what i was looking for xD

**Comment by dajojonl** [comment]
So..
http://192.168.2.14/cgi-bin/CGIProxy.fcgi?cmd=getDevInfo&usr=me&pwd=pw
```
<CGI_Result> <result>0</result> <productName>FI9818W</productName> <serialNo>0000000000000001</serialNo> <devName>YuCam Rear</devName> <mac>00626E44787B</mac> <year>2019</year> <mon>7</mon> <day>22</day> <hour>12</hour> <min>58</min> <sec>26</sec> <timeZone>-7200</timeZone> <firmwareVer>1.3.1.13</firmwareVer> <hardwareVer>1.2.1.1</hardwareVer> </CGI_Result>
```
http://192.168.2.14/cgi-bin/CGIProxy.fcgi?cmd=getImageSetting&usr=me&pwd=pw

```
<CGI_Result> <result>0</result> <brightness>61</brightness> <contrast>44</contrast> <hue>6</hue> <saturation>30</saturation> <sharpness>10</sharpness> <denoiseLevel>50</denoiseLevel> </CGI_Result>
```
http://192.168.2.14/cgi-bin/CGIProxy.fcgi?cmd=getMirrorAndFlipSetting&usr=me&pwd=pw

```
<CGI_Result> <result>0</result> <isMirror>0</isMirror> <isFlip>0</isFlip> </CGI_Result>
```
http://192.168.2.14/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig&usr=me&pwd=pw
```
<CGI_Result> <result>0</result> <isEnable>0</isEnable> <linkage>2</linkage> <snapInterval>1</snapInterval> <sensitivity>0</sensitivity> <triggerInterval>1</triggerInterval> <schedule0>281474976710655</schedule0> <schedule1>281474976710655</schedule1> <schedule2>281474976710655</schedule2> <schedule3>281474976710655</schedule3> <schedule4>281474976710655</schedule4> <schedule5>281474976710655</schedule5> <schedule6>281474976710655</schedule6> <area0>192</area0> <area1>192</area1> <area2>192</area2> <area3>480</area3> <area4>488</area4> <area5>8</area5> <area6>992</area6> <area7>992</area7> <area8>480</area8> <area9>384</area9> </CGI_Result>
```
http://192.168.2.14/cgi-bin/CGIProxy.fcgi?cmd=getProductAllInfo&usr=me&pwd=pw
```
<CGI_Result> <result>-3</result> </CGI_Result>
```

**Comment by edwinvdpol** [comment]
I asked Foscam support, but they say that nothing has changed about the CGI interface.
I'm not sure why the `getProductAllInfo` does not work with your camera.
Did you figured something out yet? Did you try to reboot your camera etc.?

**Comment by dajojonl** [comment]
Probably as it does not have the newer firmware which V2 version has. This is V1 model i have.

**Comment by edwinvdpol** [comment]
That is too bad 😞 Sorry I can't help you any further.
