### ISSUE TITLE
Can only connect as administrator

### ISSUE THREAD

**Issue by htilburgs** [edwinvdpol/com.foscam#18]
Using 4 Foscam Cameras (2x FI9853EP & 2x FI9851P).
I can only connect to the camera as administrator, not as visitor or operator.
Is this with a reason?

I prefer to connect as a Visistor.

**Comment by edwinvdpol** [comment]
Some used commands, like rebooting the camera and getting the device information, require admin privileges. Nothing I can change about that I'm afraid.

**Comment by edwinvdpol** [comment]
Closed due inactivity.

**Comment by zatross** [comment]
The installer can't seem to detect my camera when I click to install from:
 https://apps.athom.com/app/com.foscam

**Comment by zatross** [comment]
The installer can't seem to detect my camera when I click to install from:
 https://apps.athom.com/app/com.foscam

**Comment by edwinvdpol** [comment]
You do have to [add your device](https://support.athom.com/hc/en-us/articles/360009768313-How-to-add-a-device-to-Homey) in Homey when you installed the app. :wink:
