### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by Dvm08** [edwinvdpol/com.foscam#2]
Als ik mijn camera wil toevoegen krijg ik 'error' in beeld. Na het klikken van 'opslaan' moet ik ook even een paar seconden wachten. Volgens mij kloppen de gegevens wel want als ik een ander ip adres invul krijg ik een andere fout. Enige tips om te checken wat dit kan zijn?

Betreft overigens model fi9900p. Werkt wel gewoon via foscam app en ik heb een ander ip cam viewer en daar werkt hij alleen als ik op hetzelfde WiFi netwerk zit.

**Comment by edwinvdpol** [comment]
Als je zeker weet dat alle gegevens kloppen, zul je moeten wachten op een van de volgende releases.
Daarin heb ik uitgebreide logging toegevoegd, en kunnen we beter onderzoeken wat er precies fout gaat.

Wat je in de tussentijd kan doen is het volgende.
Zorg dat je op je lokale netwerk zit en ga naar de volgende URL op je telefoon / laptop:

> http://[ip]:[port]/cgi-bin/CGIProxy.fcgi

Als het goed is, krijg je iets wat lijkt op:
```
<CGI_Result>
    <result>-3</result>
</CGI_Result>
```
Wanneer je hier een 404 pagina krijgt, wordt de FI9900P waarschijnlijk niet ondersteund door de app.
Ik heb al een aantal wijzigingen in de pijplijn zitten, maar het is wachten op Athom.

**Comment by Dvm08** [comment]
Okee top. Zal het vanavond is checken en anders even de update afwachten en kijken of hij dan werkt. Thanks!

**Comment by edwinvdpol** [comment]
Versie 1.1.0 van de app is gepubliceerd in de Homey App Store en ondersteund uitgebreide logging.

**Comment by Dvm08** [comment]
Nogmaals geprobeerd maar helaas zonder succes. Typ ik expres een verkeerd ip adres of poort in dan krijg ik de melding netwerktoegang geweigerd. Dus beide heb ik goed ingevuld lijkt me zo. Alleen nu als ik alles in vul krijg ik een lege melding met alleen 'ok'. Zal het vanavond is met mn andere camera proberen. Heb helaas t ip adres daarvan niet bij de hand.

**Comment by edwinvdpol** [comment]
Kun je dan de logs die je kan zien in de app settings hier posten wanneer je de camera toe hebt geprobeerd te voegen?

**Comment by Dvm08** [comment]
Zie edited command hierboven. Was er net mee bezig :)

**Comment by edwinvdpol** [comment]
Dit is een foutmelding van de SMTP configuratie, deze is bedoeld om je e-mail server in te stellen om een snapshot te kunnen mailen. Je moet een [apparaat toevoegen](https://support.athom.com/hc/nl/articles/360009768313-Een-apparaat-aan-Homey-toevoegen) (camera) en daar de inloggegevens van je camera invullen.

**Comment by Dvm08** [comment]
O wat dom... Ik dacht dat ik hem in de app in moest stellen. Kwam natuurlijk ook mooi overeen met ip adres poort en inloggegevens. Heb em toegevoegd en ga ermee aan de gang. Camera werd direct gevonden. Sorry!

**Comment by edwinvdpol** [comment]
Gmail vinkje staat genoteerd 👍
Motion detection is eventueel wel mogelijk en had ik gister werkend, maar de app moet dan om de _x_ aantal seconden de camera pollen om te checken of het alarm aanstaat. Dit aangezien de camera's van Foscam geen 'notificatie' naar Homey kunnen sturen. Weet nog niet of dit wenselijk is...

**Comment by Dvm08** [comment]
Net geprobeerd om in te loggen en volgens mij had ik de instellingen wel goed. Maar, nu komt het. Krijg van Gmail een melding dat het een onbeveiligde login is en deze is geblokkeerd. Zie onderstaande melding. Zo eenvoudig is het dus allemaal niet :) geen idee of dit te omzeilen is? Ik krijg nu steeds de melding dat het wachtwoord niet juist is.

Iemand heeft zojuist je wachtwoord gebruikt om te proberen in te loggen op je account vanuit een niet-Google-app. Google heeft dit geblokkeerd, maar je moet controleren wat er is gebeurd. Controleer je accountactiviteit om te zorgen dat niemand anders toegang heeft.

**Comment by edwinvdpol** [comment]
Waarschijnlijk dit: [Toestaan dat minder goed beveiligde apps toegang tot uw account krijgen](https://support.google.com/accounts/answer/6010255)

**Comment by Dvm08** [comment]
Jep. Is ook gelukt👍 screenshot komt ook binnen via mail. Alleen op zijn kop maar dat is aan te passen als het goed is. Tot zo ver werkt het in ieder geval. Dat is mooi. Maak wel een apart email adres ervoor aan denk ik. Dan hou ik m'n goede email adres wel beschermd tegen die login pogingen dan kan er weinig foutgaan volgens mij. Top app.
