### ISSUE TITLE
Foscam enabling/disabling video recording

### ISSUE THREAD

**Issue by wan01524** [edwinvdpol/com.foscam#20]
Hi,
Would it be possible to add a flow card to enable/disable the video recording. I would like to use this option when I am away from home and arming the alarm system (

Regards Allan

**Comment by edwinvdpol** [comment]
Hi Allen, 

Thank you for your request. I will look into this when I have the time, and when I am back from vacation.

-- Edwin

**Comment by wan01524** [comment]
Hi Edwin,
Thank you for a quick reply. 
Enjoy your vacation.

**Comment by edwinvdpol** [comment]
> Would it be possible to add a flow card to enable/disable the video recording. I would like to use this option when I am away from home and arming the alarm system (

Does this mean, you don't use the record schedule? You cannot enable / disable the recording easily, only schedule the recordings. When I have to adjust this, you schedule will be overwritten. I don't know if this is the way to go. What do you think?

**Comment by wan01524** [comment]
My idea is not to use the build in scheduling in the cam but let it be controlled by the Homey, thereby I can build the schedule in my homey. Of cause this means there will be a conflict if the cam build in scheduler is used. An other flow card could be to disable/enable the cam build in schedule.
Another card that would be useful is disable/enable motion detection (witch starts recording to e.g. ftp server)

Regard Allan

**Comment by edwinvdpol** [comment]
Hi Allan,

The problem with the scheduling / recording is that, when you want to update a schedule, you have to overwrite all schedule (settings). So, when you want Homey to takeover the camera schedule, everything will be overwritten.
An option is to save the schedule which was programmed initially, and push these to the camera if the schedule is changed back to 'camera default'.

What are your thoughts about this?

The option to disable / enable motion detection is already build in the app :wink:

Regards Edwin

**Comment by wan01524** [comment]
Hi Edwin
Not sure I understand the problem. I can operate the cam and force it to turn recording on/off from the cam web UI. Maybe this command is not a part of the API?!
Another possibility is to go to the cam settings and create a schedule and then disable/enable the scheduled recording. This means I could create a 24/7 scheduled and from the homey enable and disable it based on whatever conditions I like. I see this possibility in 3rd party app for the foscam so I guess it’s in the API?!

**Comment by edwinvdpol** [comment]
Hi Allan,

If you can find the `record on/off` command in [this API](https://www.foscam.es/descarga/Foscam-IPCamera-CGI-User-Guide-AllPlatforms-2015.11.06.pdf), please let me know :wink:

> Another possibility is to go to the cam settings and create a schedule and then disable/enable the scheduled recording. This means I could create a 24/7 scheduled and from the homey enable and disable it based on whatever conditions I like

This is possible, good point! I guess this should be optional and off by default, else Homey will overwrite the schedule to always record. The cam records schedule settings are messed up afterwards and unmanageable with other apps, but who cares if you got a Homey? :sunglasses:

-- Edwin

**Comment by edwinvdpol** [comment]
I can add the functionality to enable / disable the schedule record ofcourse!
Then, the user will be responsible to set the schedule to 24/7 for now.

**Comment by wan01524** [comment]
Well, I think the record command set from the cam web UI is not there. But I did a small test and found that it is useless as the command triggers the recording to the local device from where it is enabled.
So for now I think the possibility to enable the scheduled recording will do it.

Regards Allan

**Comment by edwinvdpol** [comment]
This is added in v2.1.2, which is in review by Athom.

**Comment by edwinvdpol** [comment]
I hope it works now! Closing...

**Comment by wan01524** [comment]
Works fine on the Foscam FI9900EP cam I to got working. Unfortunately my other cam is not working anymore.
