### ISSUE TITLE
Feature request: support for non-admin account

### ISSUE THREAD

**Issue by gruijter** [edwinvdpol/com.foscam#22]
Hi Edwin,

Thx 4 this app. Works great. But....

I really do not want my admin password to be entered in Homey. Could you create support for non-admin accounts (i.e. operator or visitor)? I understand that not all functionality is available then. But I would only need to create snapshots and send that as email.

Thx!

**Comment by edwinvdpol** [comment]
Hi Gruijter,

Thank you for your request! I got this request earlier this year (#18).
When I have the time, I will look into the possibilities, and what consequences this has for the rest of the app!

Thanks!

**Comment by edwinvdpol** [comment]
Hi gruijter,

I looked at the possibilities, but it is a lot of work to customise the app for this.

If you only need the snapshot function of the camera, I advice you to use the [Homey Virtual IP Camera](https://support.athom.com/hc/nl/articles/360024401113-Virtuele-Apparaten-Experiment) functionality.

You can use the URL below:
`http://{ip]:{port}/cgi-bin/CGIProxy.fcgi?usr={user}&pwd={pass]&cmd=snapPicture2`

-- Edwin
