### ISSUE TITLE
Homey Connection refused

### ISSUE THREAD

**Issue by pulsebreaker** [edwinvdpol/com.foscam#23]
After adding a Foscam C1 to Homey it worked perfectly for a while. A couple of weeks ago Homey could'nt find it anymore. Deleted and adding the camera does not work, I get a connection refused (connect ECONNREFUSED). I can connect to it from the standard app and through a webbrowser using the same credentials.

**Comment by edwinvdpol** [comment]
Can you try to reach the following URL on your phone/computer when connected to your local network?
**Please post the response in this issue.**

http://[ip]:[port]/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig1&usr=[user]&pwd=[pass]

If that URL doesn't work, please try this one:

http://[ip]:[port]/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig&usr=[user]&pwd=[pass]

Thanks!

**Comment by pulsebreaker** [comment]
Works!

Result:

<CGI_Result>
    <result>0</result>
    <isEnable>0</isEnable>
    <linkage>137</linkage>
    <snapInterval>1</snapInterval>
    <triggerInterval>0</triggerInterval>
    <isMovAlarmEnable>1</isMovAlarmEnable>
    <isPirAlarmEnable>1</isPirAlarmEnable>
    <schedule0>281474976710655</schedule0>
    <schedule1>281474976710655</schedule1>
    <schedule2>281474976710655</schedule2>
    <schedule3>281474976710655</schedule3>
    <schedule4>281474976710655</schedule4>
    <schedule5>281474976710655</schedule5>
    <schedule6>281474976710655</schedule6>
    <x1>0</x1>
    <y1>0</y1>
    <width1>10000</width1>
    <height1>10000</height1>
    <threshold1>0</threshold1>
    <sensitivity1>2</sensitivity1>
    <valid1>1</valid1>
    <x2>0</x2>
    <y2>0</y2>
    <width2>0</width2>
    <height2>0</height2>
    <threshold2>0</threshold2>
    <sensitivity2>2</sensitivity2>
    <valid2>0</valid2>
    <x3>0</x3>
    <y3>0</y3>
    <width3>0</width3>
    <height3>0</height3>
    <threshold3>0</threshold3>
    <sensitivity3>2</sensitivity3>
    <valid3>0</valid3>
</CGI_Result>

Groet,

Arno

Op za 30 nov. 2019 om 21:08 schreef Edwin van de Pol <
notifications@github.com>:

**Comment by pulsebreaker** [comment]
I think it's a Homey thing. When I try to add the camera as a 'virtual IP
camera' using the same URL as on my laptop I get the same error message
(connect ECONNREFUSED).

I don't think it's your app.

Regards,

Arno

Op za 30 nov. 2019 om 21:08 schreef Edwin van de Pol <
notifications@github.com>:

**Comment by edwinvdpol** [comment]
That it weird indeed. Have you tried rebooting Homey?
As it is a Homey issue, Can you please ajust or remove the 2 * rating in the Homey store? 😉
