### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by josjg** [edwinvdpol/com.foscam#24]
Hello Edwin,

Thanks for your nice app.
I want to use my Foscam R2 as a motion detector as well. Is it possible to add the motion detected trigger for Foscam cameras?

Thanks,

Jos

**Comment by edwinvdpol** [comment]
Hi Jos,

Thank you for your kind words, I'm glad you like it!

The reason why this is not implemented is stated [here](https://github.com/edwinvdpol/com.foscam/blob/master/MOTION.md).

Hope this helps!

-- Edwin

**Comment by josjg** [comment]
Bedankt Edwin! Duidelijk.




Kind regards,


Jos Gielen
EMCI Registered Yacht Broker

[cid:image001.png@01D5B678.D9BCAF90]

T:
+351 21 218 7775
M:
+351 91 472 5758
S:
si.portugal
W:
www.tulipyachts.com<http://www.tulipyachts.com>
E:
info@tulipyachts.com<mailto:info@tulipyachts.com>


Van: Edwin van de Pol <notifications@github.com>
Verzonden: donderdag 19 december 2019 14:16
Aan: edwinvdpol/com.foscam <com.foscam@noreply.github.com>
CC: Jos Gielen <jos@tulipyachts.com>; Author <author@noreply.github.com>
Onderwerp: Re: [edwinvdpol/com.foscam] Feature Request (#24)


Hi Jos,

Thank you for your kind words, I'm glad you like it!

The reason why this is not implemented is stated here<https://github.com/edwinvdpol/com.foscam/blob/master/MOTION.md>.

Hope this helps!

-- Edwin

**Comment by edwinvdpol** [comment]
Implemented! 🎉
