### ISSUE TITLE
[REQ] PTZ preset

### ISSUE THREAD

**Issue by MrBlue90** [edwinvdpol/com.foscam#3]
Could you please add a flowcard for triggering a PTZ preset?
By this you can easily move the camera as soon as a motion sensor or doorbell is triggered.

**Comment by MrBlue90** [comment]
API call should be http://IP:PORT/cgi-bin/CGIProxy.fcgi?cmd=ptzGotoPresetPoint&name=PTZ_NAME&usr=Username&pwd=Password

**Comment by edwinvdpol** [comment]
Nice idea, I've put it on the todo list 👍
Unfortunately, I do not own a camera which support PTZ.
When I have a version available, are you willing to test this functionality?

**Comment by MrBlue90** [comment]
Sure!
Still need to upgrade to v2, but happy to test as soon as it's available 👌🏼

**Comment by Ruudje007** [comment]
Good addition option!

I will help you also in testing your app and this functionality!

**Comment by MrBlue90** [comment]
While you're at it, cruzing is pretty similar to presets:

Start
/cgi-bin/CGIProxy.fcgi?cmd=ptzStartCruise&mapName=test&usr=admin&pwd=

Stop
/cgi-bin/CGIProxy.fcgi?cmd=ptzStopCruise&usr=admin&pwd=

**Comment by edwinvdpol** [comment]
This request is already done in v1.2.0 which is pending at Athom. 

Please make a new request if you will.

And how does it work? When do you have to stop the cruise? Some information would been nice, as I don't own a PTZ camera.

**Comment by edwinvdpol** [comment]
Like, when you _start_ cruising, the camera goes from 1 point to another and keeps doing it until you _stop_ the cruising? Maybe I can squeeze it in.

**Comment by rnldnkp** [comment]
I like this idea, have been using the URL to do this without a specific app. Calling the preset works very nice. 

IF motion backyard 
AND not home OR sleeping
THEN set preset, take snapshot, send using telegram (for example)

Problem is, the PTZ presets are not that accurate in my opinion. So, after moving between presets it's not in the position it started at... Has anybody else had the same issue? (although this does not prevent this feature being added of course)

**Comment by edwinvdpol** [comment]
Version 1.2.0 is released and supports PTZ presets.
