### ISSUE TITLE
Error after update to V1.2.0

### ISSUE THREAD

**Issue by PatrickvanD** [edwinvdpol/com.foscam#5]
After update to latest version i got an error.

Error: U heeft niet voldoende rechten om deze camera te beheren. at rp.then.response (/lib/Api.js:68:35) at at process._tickCallback (internal/process/next_tick.js:189:7) 

I also tried a fresh install

**Comment by edwinvdpol** [comment]
Hi Patrick,

Do you have a Foscam R2, R4 or C2?
Please read [this issue](https://github.com/edwinvdpol/com.foscam/issues/4).

If you do not, please submit a diagnostic report 👍

**Comment by PatrickvanD** [comment]
Hi Edwin, yes i have a R4. Thx. For the fast response.

**Comment by edwinvdpol** [comment]
No problem, working on the fix right now! Please be patient. ;-)

**Comment by edwinvdpol** [comment]
The app is published. Can you please let me know if it works?

**Comment by PatrickvanD** [comment]
Hi Edwin, i have no more error. Thank you for the good work!
