### ISSUE TITLE
Foscam R2

### ISSUE THREAD

**Issue by henkhuppelschoten** [edwinvdpol/com.foscam#6]
**Describe the issue**
If i connect to my R2 PT camera's, Homey sas that i do not have the rights for this camara. I'dd logged in whit acceptence. With another foscam camera i do have the rights.

**Expected behavior**
That i can control my camera like i'dd should

**CGI result**
```
<CGI_Result>
    <result>-3</result>
</CGI_Result>

**More information**
- Homey firmware version: [e.g. 2.0.0]
- App version [e.g. 1.1.0]
- Camera model R2

**Additional context**
Add any other context about the problem here.

**Comment by edwinvdpol** [comment]
Please read [this issue](https://github.com/edwinvdpol/com.foscam/issues/4).
Waiting for Athom to approve the new version.

**Comment by henkhuppelschoten** [comment]
Thank you for the responce, did not see that post.

i'dd wait for the update.

**Comment by edwinvdpol** [comment]
The app is published. Can you please let me know if it works?

**Comment by henkhuppelschoten** [comment]
Yes of Works thanxs

Op di 12 mrt. 2019 11:11 schreef E. van de Pol <notifications@github.com>:

**Comment by edwinvdpol** [comment]
Awesome! Thanks!
