### ISSUE TITLE
Ongeldig antwoord van het netwerk apparaat gekregen

### ISSUE THREAD

**Issue by powermarcel10** [edwinvdpol/com.foscam#8]
Hallo,

Eindelijk support voor Foscam camera's. Super! 

Ik krijg die van mij alleen niet toegevoegd omdat ik bovenstaande melding krijg. 

Ik heb een Foscam R2 camera. (nieuwste firmware) 

Ik gebruik poort 888, dit is namelijk de poort die ik in tinycam pro te zien krijg, het juiste IP adres en de juiste inloggegevens. 

Ik gebruik versie 1.2.1 van je app op de laatste Homey 2.0.5 rc. 

Enig idee wat er mis gaat?

**Comment by edwinvdpol** [comment]
Hi Marcel,

Kun je (een stukje) van de logs hier posten wanneer het mis gaat?

**Comment by powermarcel10** [comment]
Tuurlijk!

2019-03-13 23:22:34 [log] [ManagerDrivers] [pt] Start pairing device 
2019-03-13 23:19:19 [log] [ManagerDrivers] [pt] Validate pair settings 
2019-03-13 23:19:08 [log] [ManagerDrivers] [pt] Validate pair settings 
2019-03-13 23:18:39 [log] [ManagerDrivers] [pt] Start pairing device 
2019-03-13 23:18:09 [log] [ManagerDrivers] [pt] Start pairing device 
2019-03-13 23:17:19 [log] [App] Unloading app... 
2019-03-13 23:12:26 [log] [ManagerDrivers] [pt] Validate pair settings 
2019-03-13 23:12:23 [log] [ManagerDrivers] [pt] Validate pair settings 
2019-03-13 23:12:21 [log] [ManagerDrivers] [pt] Validate pair settings 
2019-03-13 23:12:19 [log] [ManagerDrivers] [pt] Validate pair settings 
2019-03-13 23:12:12 [log] [ManagerDrivers] [pt] Validate pair settings 
2019-03-13 23:11:47 [log] [ManagerDrivers] [pt] Start pairing device 
2019-03-13 23:01:56 [log] [ManagerDrivers] [pt] Start pairing device 
2019-03-13 23:01:37 [log] [App] com.foscam running... 
2019-03-13 23:01:37 [log] [App] Capturing stderr...

**Comment by edwinvdpol** [comment]
Ik zie in dit stuk log geen foutmelding. Kun je een foutmelding vinden ergens?
Wanneer krijg je de melding? Bij het toevoegen van de camera?

**Comment by powermarcel10** [comment]
En dit krijg ik te zien als ik hier naar toe ga:

http://192.168.2.36:888/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig1&usr=powermarcel10&pwd=(wachtwoord) 

<SOAP-ENV:Fault xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:wsc="http://schemas.xmlsoap.org/ws/2005/02/sc" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:tdn="http://www.onvif.org/ver10/network/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl">
<faultcode>SOAP-ENV:Client</faultcode>
<faultstring>HTTP GET method not implemented</faultstring>
</SOAP-ENV:Fault>

**Comment by powermarcel10** [comment]
Ik krijg de melding inderdaad bij het toevoegen van de camera

**Comment by powermarcel10** [comment]
Hij is nu ineens wel toegevoegd! Ik moest toch poort 88 invullen. Al had ik dat dacht ik ook al geprobeerd.

Never mind. Het lijkt te werken! Excuus voor je tijd!

**Comment by edwinvdpol** [comment]
Top! Veel plezier ermee 👍

**Comment by powermarcel10** [comment]
Hoi Edwin, nog even een vraag.. Klopt het dat er geen triggers beschikbaar zijn? Zoals bij beweging? Hier had ik stiekem op gehoopt..

Dus: ALS de camera beweging detecteert, DAN.......

**Comment by edwinvdpol** [comment]
Hi Marcel,

Technisch gezien is dit mogelijk en heb het al een keer werkend gekregen. Het nadeel van de Foscam camera's is dat ze geen 'notificaties' kunnen sturen. Dus Homey zou om de _x_ aantal seconden een request naar de camera moeten sturen en kijken of er beweging gedetecteerd is.

Dit is voor 1 camera prima, maar als je 4 of 5 camera's hebt die elk om de 1 of 2 seconden een request sturen, is dit misschien niet ideaal voor het netwerk en/of voor Homey.

Ik zat er nog wel over na te denken, om dit instelbaar te maken per camera met daarbij de interval.
Ik kan hier in de toekomst nog wel naar kijken 👍

**Comment by powermarcel10** [comment]
Aaah ik begrijp het. Een beetje met zoals de Hue app van homey werkt. Die pollt ook de bridge elke 5 seconden. Bedankt. Voor de opheldering!

Ik zou het persoonlijk wel fijn vinden als de optie er was dus ik zal de updates in de gaten houden! 

Wel is er de trigger voor wanneer er een snapshot wordt gemaakt. Ik begrijp alleen niet hoe dit werkt. Als ik in de Foscam app een foto maak komt dit niet door in homey als ik hier een flow mee maak. 

Is er ergens documentatie van hoe ik dit instel?

**Comment by edwinvdpol** [comment]
Alleen als je de Flowcard "**DAN** _maak een snapshot_" gebruikt, wordt deze trigger aangeroepen.
Homey moet de snapshot maken. Hij weet niet wanneer jij een snapshot maakt met een andere app / apparaat. :blush:
